Okay, here's the translated and formatted information from the provided text, organized by page:

# **Energy**

*   Classification of Energy
*   Major Energy Projects of Rajasthan
*   Energy-Related Institutions
*   Energy-Related Schemes
*   Other Important Points

## **[A. Classification of Energy Resources]**
### Based on Potential:
| Renewable | Non-Renewable |
|------------------|-------------------|
| 1. Hydro/Water | 1. Thermal Energy
|2. Solar Energy |   * Coal
|3. Wind Energy |    * Natural Gas
|4. Biogas   |    * Petroleum
|5. Biomass   | 2. Nuclear Energy
|6. Tidal Energy |     * Uranium
|7. Geothermal Energy |  * Thorium

###  Based on Production:
| Traditional   | Non-Traditional |
|----------------|-----------------|
|1. Coal |1. Nuclear Energy|
|2. Natural Gas  |2. Solar Energy|
|3. Petroleum |3. Wind Energy|
|4. Hydro/Water Energy |4. Biomass|
|   |5. Biogas|
 |   |6. Tidal Energy|

**(a) Traditional Energy Resources:** Those energy resources that have been used for a long time and from which energy is produced using old technology.
*   Example: Hydropower, thermal energy (coal, gas, petroleum)

**Page 10**

**(b) Non-Traditional Energy Sources:** Those energy resources that have been in use for a long time and from which energy is produced using new technology.
     *  Example: Nuclear energy, wind energy, solar energy, biomass energy, etc.

*  **Note:** Types of Energy Stations based on production capacity:
    * **Super Station:** A station that produces more than 1000 MW of energy.
    *  **Super Critical Station:** A unit that produces more than 500 MW of energy.
    *   **Ultra Mega Power Project (UMPP):** A station that produces more than 4000 MW of energy.
## **B. Major Energy Projects of Rajasthan**
    *  **Energy Projects in Rajasthan**

|  Traditional Energy    | Non-Traditional Energy     |
|--------------|-------------------|
    
###  **I. Traditional Energy** - Hydro and Thermal Energy
  ###  **Hydro Energy**
     *   **(a) State Government**
       *   **(b) State-State**
        *   **(c) Central Government**

**Page 229**
## **1. Hydro Energy of State Government:**
    *   1. **Jakham Small Hydro Energy Projects** - Pratapgarh
          *  Production Capacity - 5.4 MW
    *   2. **Anas Hydroelectric Project:** - Banswara
          *  Production Capacity - 140 MW
     *  3. **Indira Gandhi Small Hydroelectric Project:** Sri Ganganagar, Bikaner
           *   Production Capacity - 23.85 MW
## **2. Hydroelectric Projects of State : State Cooperation:**
    *   **Bhakra-Nangal Hydroelectric Project**
       *   Benefited States: Rajasthan, Punjab, Haryana
       *   Production Capacity - 1493 MW
        *   Rajasthan's share - 15.2 percent (227 MW)
    *  **Beas Hydroelectric Project**
        * States: Rajasthan + Punjab
        *  Rajasthan's share - 422 MW
     *  **Mahi-Bajaj Sagar Hydroelectric Project:**
         * Benefited states: Rajasthan and Gujarat (45:55)
         *  This project is built in two phases:
            *   2 x 25 MW = 50 MW
             *   2 x 45 MW = 90 MW
     *  100% of the energy produced in this project is distributed in the tribal region of Rajasthan. (140 MW)

**Page 230**
     *  **Chambal Hydroelectric Project**
         *  Joint project of Rajasthan and MP.
         *  Contribution of both the states (50:50)
      *  The total hydroelectric power generation from three dams in this project is 386 MW:
         *  Gandhi Sagar - 93 MW x 5 (115 MW)
         *  Rana Pratap Sagar - 43 MW x 3 (172 MW)
            *  Jawahar Sagar - 33 MW x 3 (99 MW)
          * Total = 386 MW (Rajasthan - 193 MW : Madhya Pradesh - 193 MW)
      *  **Rahughat Project** - Karauli
           *  Project located on Chambal River
           *   Joint project of Rajasthan + Madhya Pradesh (50:50)
           *  Production capacity - 79 MW
## **3. Central Government's Hydroelectric Projects:**
    *   **Salal Project:** (Jammu and Kashmir)
          *  On the Chenab River
         *  Operated by NHPC (National Hydroelectric Power Corporation).
         *   Jammu and Kashmir, Rajasthan, U.P., Punjab, Haryana, Delhi, H.P. and Chandigarh are benefited from this project.
     *  **Dulhasti Project** (Jammu and Kashmir)
         * Operated by NHPC

**Page 231**
      * On Chenab River
       * Jammu and Kashmir, Rajasthan, U.P., Punjab, Haryana, Delhi, Uttarakhand and Chandigarh are benefited from this project.
      *  **Uri Project:** (Jammu and Kashmir)
            * On the Jhelum River
             * Operated by NHPC
             * Jammu and Kashmir, Rajasthan, U.P., Punjab, Haryana, Delhi, H.P., Uttarakhand and Chandigarh are benefited from this project.
      *   **Parvati Project:** (Himachal Pradesh)
           *   On the Parvati River
            * Operated by NHPC
    * **Chamera Project:** (Himachal Pradesh)
        *  On the Ravi River (Operated by NHPC)
    *  **Nathpa Jhakri Project:** (Himachal Pradesh)
         *  On the Satluj River (Operated by NHPC)

**Page 232**

*  **Tehri Project** - (Uttarakhand)
        *  This project is operated by Tehri Hydro Development Corporation Limited on the Bhagirathi and Bhilangana rivers.
*  **Lakhwar Project** - (Uttarakhand)
          *   Operated by NHPC on the Sada (Kali) river.
    *   **Dhauliganga Project** - (Uttarakhand)
        * This project is operated by NHPC on the Dhauliganga river.

     *[(India Map with locations marked)]*
        *   Jammu (Chenab)
       * Parvati (Parvati)
       * Nathpa-Jhakri (Satluj)
       *   Sulal (Chenab)
     *  Dulhasti (Chenab)
        *  Uri (Jhelum)
    *  Tehri (Bhagirathi)
         * Lakhwar (Kali River)
     *  Dhauliganga
**Page 233**

*Conclusion:*
    *  More development and planning are needed in hydroelectric projects to increase energy production and improve energy security in Rajasthan.
###  **Thermal Energy:** (Thermal Power Projects of the State of Rajasthan):-
   * The main sources of this energy are coal, petroleum, and natural gas.
       *  Coal contributes the most to power generation in thermal projects.
    *   **(A) Coal/Lignite Based Projects:**
         * (a) Schemes of State Government (b) Schemes of State: State (c) Schemes of Central Government
### **Schemes of State Government:**
    * 1.  **Suratgarh Super Critical Thermal Power Plant** - Sri Ganganagar
         *   A total of 2820 MW of energy is produced from 8 units in five stages at Suratgarh Thermal Plant. Which includes:
| Phase   | Unit   | Production Capacity |
|-------------|------------|-----------|
|I | Unit-1st|250 MW  |
|I |Unit-2nd   |250 MW |
|II  |Unit-3rd   |250 MW  |
|II  |Unit-4th   |250 MW  |
|III  |Unit-5th   |250 MW   |
|III  |Unit-6th  |250 MW   |
|IV |Unit-7th  |660 MW   |
|V  |Unit-8th   |660 MW    |
**Page 234**
 *  This is the first super thermal (2000) power plant in Rajasthan. Which is currently (2024) the largest thermal power project in Rajasthan.
 *  2. **Kota Super Thermal Power Plant:**
      *   It is the first (1983) thermal (coal) power plant in Rajasthan.
      *  It is the first thermal power project of Rajasthan, while it is the second super thermal power project.
      *  A total of 1240 MW of energy is produced from 7 units in five stages at Kota Thermal Plant. Which includes:
| Phase   | Unit   | Production Capacity  |
|--------|----------------|----------------|
|  I   |  Unit-1st | 110 MW |
|I |Unit-2nd|110 MW |
|II |Unit-3rd |210 MW  |
|II |Unit-4th |210 MW  |
|III |Unit-5th |210 MW   |
|IV |Unit-6th  |195 MW  |
|V  |Unit-7th |195 MW  |

 * 3.  **Chhabra Super Critical Power Plant:** - Baran
        *   Production capacity - 2320 MW
         * It is the first critical thermal power project in Rajasthan.

| Phase   | Unit   | Production Capacity |
|--------|----------------|----------------|
|I|Unit-1st |250 MW |
|I|Unit-2nd   |250 MW  |
|II  |Unit-3rd  |250 MW  |
|II |Unit-4th  |250 MW  |
|III |Unit-5th   |660 MW  |
|III|Unit-6th |660 MW  |
**Page 235**
 *  4. **Kawai Super Critical Power Plant:** - Baran
         *  Production Capacity - 1320 MW
          *  Collaboration - Adani Group
| Phase   | Unit   | Production Capacity  |
|-----------|----------------|-----------------|
| I     | Unit - 1st | 660 MW |
| I     | Unit - 2nd | 660 MW  |

**Page 236**
*  5. **Kali Sindh Critical Power Plant:** - Jhalawar
      *  Production capacity: 1200 MW
     *  Proposed: 800 MW (Adani Power Project)
  *  6. **Bhadesar Super Power Plant** - Barmer
      *    Production Capacity - 1080 MW
    *  7. **Kapurdi - Jaliyapa Super Thermal Power Plant:** - Barmer
        *   Production Capacity - 1080 MW
   *  8. **Giral Thermal Power Plant:** - Gurhali Village, Barmer
         *   Production Capacity - 250 MW
          *  Collaboration - Germany
    *   9. **Dhanpur Super Thermal Power Project:** - Banswara
            *   Production Capacity - 1600 MW
       *  10. **Barsingsar Thermal Power Project:** - Bikaner
             * Production capacity = 250 MW
          *   It is operated by Neyveli Lignite Corporation (Government of India).
(b) **State: State Scheme:**
    * 1. **Satpura Thermal Power Project:**
         * Location - District Betul, Madhya Pradesh
          *  Benefited States: Rajasthan + Madhya Pradesh

**Page 237**
(c) **Central Government Project**

| Scheme   | Location    |  Operating Agency |
|--------------------------------|--------------|------------------------|
| Vindhyachali Thermal Plant    | U.P | NTPC     |
| Rihand Super Thermal Power Plant     |  U.P |  NTPC |
| Unchahar Super Thermal Power Plant  | U.P | NTPC     |
| Kahalgaon Super Thermal Power Plant  |  Bihar   |  NTPC |
| Talcher Super Thermal Power Plant | Odisha  | NTPC  |
##  **Gas Based Power Projects**
    *    (a) Schemes of State Government (b) Schemes of Central Government
###  **1. Schemes of State Government:**
| Gas Power Project | Location  | Production Capacity  |
|-------------------|---------------------|----------------------|
| 1. Ramgarh    | Jaisalmer  | 270.5 MW      |
| 2. Combined Cycle    | Dholpur    | 330 MW      |
| 3. Sagar-Kotra | Udaipur  | -   |
  *  **Note:** The first gas-based power project of the State Government is Ramgarh (1996).

**Page 238**
(b) **Gas Power Projects of Central Government (NTPC)**

| Gas Power Project | Location | Production Capacity |
|-------------|------------------|------------------|
| 1. Unta (Bhadawar, Vijaypur, Jagdishpur Gas Pipeline) |Baran     | 419.3 MW        |
| 2. Badari        | U.P        | 829.78 MW       |
| 3. Auraiya          | U.P      | 652 MW        |
 * **Note:** First (1989) gas power project in Rajasthan operated by NTPC (Central Government) → Unta Gas Power Plant

### **Coal/Liquid Fuel Based Projects:**

   *  1.  **Dholpur Power Plant** - 1st Phase = 330 MW, 2nd Phase = 372.7 MW
         *  Total = 702.7 MW
     *  2.  **Keshoraipatan Thermal Power Plant:** - Bundi

### 5. Non-Conventional Energy
### 1.  Nuclear Energy
    *   Rajasthan Nuclear or Atomic Power Station: Rawatbhata (Chittorgarh)
        *   Start: December, 1973 (Cooperation - Canada)

**Page 239**

*  **Rajasthan ka Bhugol**
    *   Operator: Department of Nuclear Energy (NPCIL)
    *   The total installed capacity of 6 units of this plant is 1180 MW.
| Unit   | Production |
|-----------------|------------|
|First Unit| 100 MW     |
|Second Unit | 200 MW     |
|Third Unit| 220 MW   |
|Fourth Unit | 220 MW  |
|Fifth Unit  | 220 MW     |
|Sixth Unit   | 220 MW      |
|**Total Capacity**   | **1180 MW**      |

*   Two units of 700 MW are proposed at Rawatbhata Nuclear Power Plant.
    *   Rajasthan receives nuclear power from Rawatbhata (Rajasthan) and Narora (U.P.).
    *   The second nuclear power plant in Rajasthan - Banswara (Proposed)
       *  700 MW × 4 Unit = 2800 MW
###  **Solar Energy:**
        *   Highest potential for solar energy in India
        *  Jodhpur in Rajasthan.
**Page 240**
*  **Rajasthan ka Bhugol**
 * The following are the reasons for the highest potential of solar energy in Rajasthan:
     * High intensity of solar radiation.
     *  The state has about 305 clear sunny days in a year.
      * Investors invest more in solar energy projects.
      *  Due to the vast desert expansion, high temperatures are achieved.
 *    **Note:** According to the assessment of the Ministry of New and Renewable Energy, Government of India, there is a potential to generate 142 gigawatts (1,42,000 megawatts) of solar energy from solar sources in Rajasthan.
###  **Efforts Being Made for Solar Energy Development in Rajasthan:**
 1.  **Solar Park Construction Scheme:**
         * Jodhpur, Barmer, Jaisalmer, and Bikaner have been selected for this scheme in Rajasthan.
           *   Under the agreement between the Clinton Foundation and the State Government in 2010, the Clinton Foundation will provide necessary assistance for the development of solar parks.
          *   Solar parks established in Rajasthan:
                *   Bhadla (Jodhpur)
            *   Ghusar (Jaisalmer)
            *   Phalodi Pokhran Solar Park (Jodhpur-Jaisalmer)
            *   Nokh Solar Park (Jaisalmer)
             *   Nadia Kala (Jodhpur)
            *   Fatehgarh Solar Park (Jaisalmer)
             *   Pawal Solar Park (Jaisalmer)
**Page 241**
*  **Rajasthan ka Bhugol**
    * Bhadla Solar Park
        *   Location- Jodhpur
         *  A solar park of 2245 MW has been developed in Bhadla in four phases.
        *   Bhadla Solar Park Phase
            | Phase | Production | Collaboration  |
            | ----------- | -------------- | -------------------- |
            | Ist | 65 MW | Rajasthan Solar Park  |
            | IInd | 680 MW   | Welspun Company Limited |
            | IIIrd| 1000 MW | IL & FS + State Government |
            | IVth | 500 MW   | M/s Adani + State Government  |
*   Rajasthan's first private sector solar project was started by Reliance in Dhokher (Nagaur).
 4.  **Construction of Solar City:**
         *   The cities that have the highest solar energy potential will be developed as solar cities.
       *  Jaipur, Jodhpur, and Ajmer will be included in it.
        *  Proposed Districts - Pushkar (Ajmer), Jaisalmer
 5. **SEEZ** - (Solar Energy Enterprises Zone)
  *    The region with the highest potential for solar energy in Rajasthan is called SEEZ.
     *    Areas Included: Jodhpur, Barmer, Jaisalmer.

**Page 242**

*   **Rajasthan ka Bhugol**
 *   4. **Solar Energy Mission:**
        *  Jawaharlal Nehru National Solar Mission was launched in the country for the development of solar energy.
           *  Start: January, 2010
           * Target: Production of 1 lakh MW (100 GW) solar energy by 2022
             *   This mission will be carried out in three phases.
               * First Phase (2010-13)
                * Second Phase (2013-17)
                 * Third Phase (2017-22)
  *  5. **Solar Energy Policy:**
      *   In Rajasthan:
           *   First solar energy policy: 2011
           *   Second solar energy policy: 2014
           *  Latest solar energy policy: 18 Dec. 2019
**Page 243**
*  **Rajasthan ka Bhugol**
|  Solar Energy Policy   |   |   |
|-------------------------|-----------------------------|--------------------------------|
|  *Solar Energy Policy* | *Target*       |*Vision and Objectives*|
 *   This policy will be known as the Solar Energy Policy 2019.
  *   **Target Date:** 18 Dec 2019
       *   Target: To achieve the target of 30,000 MW solar energy projects by 2024-25.
           * To create a conducive environment for heavy investors in the field of solar energy production.
           *   To achieve energy security at the national level.
            *  To achieve goals like facing the challenges of climate change.
            *(i) Utility/grid-scale solar parks -> 24,000 MW (ii) Distributed Generation -> 4000 MW (iii) Solar Rooftop -> 1000 MW (iv) Solar Pumps -> 1000 MW
### **3. Wind Energy:**
       *   According to a study conducted by the National Institute of Wind Energy of the Ministry of New and Renewable Energy, Government of India at a height of 150 m, the power generation capacity of wind energy in Rajasthan is approximately 127 gigawatts.

**Page 244**
*   **Rajasthan ka Bhugol**
*  **Note:** Jaisalmer has the highest potential for wind energy in Rajasthan.
*  **Major Wind Power Plants:**
         * Amarsagar --> Jaisalmer (1st in Rajasthan)
           *   Roda Chauhan --> Jaisalmer
            *   Rohera --> Jaisalmer
             *   Akal --> Jaisalmer
              *  Harsua --> Jaisalmer
            *   Deogarh --> Pratapgarh (3rd in Rajasthan)
          *  Beethri --> Phalodi (3rd in Rajasthan)
          *   Harks Wind Energy --> Sikar
          *   Bada Bagh --> Jaisalmer
          *   Hardid Wind Energy Plant --> Jaisalmer
        * **Note:** M/s Kalakshi Industries has established the first private sector wind energy project in Bada Bagh (Jaisalmer).

|             |      |
|----------------------------|------------------------------------------|
|Largest Wind Energy Park in Rajasthan|Bada Bagh" (Jaisalmer)|
|First Railway Wind Power Plant|Kothiasar (Jaisalmer)  |
|Highest Contribution to Wind Energy|Suzlon Energy|

*   Wind Energy Policy
    |  Wind Energy Policy |
 | Target  |
    *Vision and Objectives*
     * Nodal Agency
**Page 245**
*   **Rajasthan ka Bhugol**
### **Wind Energy**
    * This policy will be known as the Rajasthan Wind and Hybrid Energy Policy - 2019.
     * Target: 18 Dec 2019
    *   Target: To achieve the target of 8600 MW of wind and hybrid energy projects by 2024-25.
        *  Hybridization of existing Wind/Solar Plants -> 260 MW
        * New Wind - Solar Hybrid Project -> 2000 MW
        *   Wind - Solar Hybrid with Storage System -> 500 MW
       *  Hybridization of existing Conventional Plants -> 800 MW
         *   **Vision and Objectives:**
             *    To promote wind power projects and necessary storage systems.
             * To promote wind energy projects.
            *    Strengthening the transmission and distribution network in the state for integration of renewable energy.
             * To promote wind resource assessment.
            *    To promote industries related to the manufacturing of wind energy equipment.
            *   Hybridization of wind and solar technologies to address the challenges of grid safety and stability with the highest utilization of land resources and transportation systems.
**Page 246**
*  **Rajasthan ka Bhugol**
*    Rajasthan Renewable Energy Corporation will act as the nodal agency for solar energy and wind energy and will perform the following functions:
       *    -> Registration of projects
          *   -> Approval of projects
          *   -> Development of wind parks/solar parks
          *   -> Facilitating the allotment of government land
### 4. **Biomass Energy**
*   The main sources of biomass energy in Rajasthan are mustard oil, Vilayati babool, rice husk.
*  The highest potential for biomass energy is in Sri Ganganagar district.
###  **Major Biomass Power Plants:**
 | Biomass Plant   | Location   |
| ----------- | ----------------|
| Padampur | Sri Ganganagar   |
| Khatoli   | Uniyara (Tonk)     |
| Changpur   | Kota |
| Raviriya  | Chittorgarh |
| Sancharia  | Hanumangarh |
| Karela-Bagsari | Sanchore    |
    *   First biomass energy plant in Rajasthan - Padampur (Sri Ganganagar)
### 5.  **Biogas Energy**
       *   Source: Cow Dung
        *   Highest potential: Udaipur
**Page 247**
*  **Rajasthan ka Bhugol**
* **Chemical composition of biogas:**
        *   Methane = 65%
       *  CO2 = 30%
        *  Hydrogen = 5%
### **6. Biofuel / Biodiesel Energy**
  *  Biofuel/Biodiesel is considered important as diesel.
   *   The main source of biodiesel is Jatropha/Ratanjot and Karanj.
   *  For the development of biodiesel in Rajasthan, a biodiesel refinery is established in Kalarwas (Udaipur).
   *  A biodiesel plant in the state: Samarkheda (Udaipur)
##   **C. Energy Related Institutions**

### 1. **Rajasthan Renewable Energy Corporation:**
        * Objective: To develop and conserve non-conventional energy sources in the state.
        * Establishment: 9 Aug 2002
       *   Rajasthan Renewable Energy Corporation was formed by merging REDA + RSPCL.
          * REDA -> Rajasthan Energy Development Agency : 1985
           * RSPCL -> Rajasthan State Power Corporation Ltd: 1995
    *  NOTE+ RSDCL-> Rajasthan Solarpark Development Company
        *  Establishment: 2 Nov. 2011 (Jaipur)
          *   It is a subsidiary company of Rajasthan Renewable Energy Corporation.
**Page 248**
*   **Rajasthan ka Bhugol**
    2. Rajasthan State Power Generation Corporation- Jaipur
    3. Rajasthan State Power Transmission Corporation- Jaipur
    4. Rajasthan State Power Distribution Corporation- Jaipur
    5. Rajasthan State Power Distribution Corporation- Ajmer
    6. Rajasthan State Power Distribution Corporation- Jodhpur
## **D. Major Energy Related Schemes**

### 1.  **Ujjwal DISCOM Assurance Yojana (UDAY):**
    *  Start: 5 November 2015 (by the Ministry of Power, Government of India)
   * Under this scheme, the Government of India signed a tripartite MoU with the State Government and each DISCOM on 27 January 2016.
    *   The main objective of this scheme is to improve the financial condition of various companies (DISCOMs).
### 2. **Saubhagya Scheme** (PM Sahaj Har Ghar Bijli Yojana): 25 Sep. 2017
      *  Objective: To provide electricity to every household in the country. (Target year - 31 March 2019)
### 3. **Kusum Scheme (KUSUM- Kisan Urja Suraksha evam Utthan Mahabhiyan Scheme)**
   *  Start: 2018-19
        *  Energy Target: 30800 MW
          * Objective:
                 *  (i) To install solar pumps and connect them to the grid.
                *   (ii) To provide energy security to farmers.

**Page 249**
*   **Rajasthan ka Bhugol**
**(a) Kusum Component - A:**
   *  **Establishment:** Decentralized solar power plants with a capacity of 0.5MW to 2MW
    *   **Location:** On the barren land of the farmers located within a radius of 5 km of 33/11 kV Rajasthani stations
      *    **Operation:** Rajasthan Renewable Energy Corporation
**(b) Kusum Component-B:**
    *   A target of 12,500 pump sets has been set to solarize agricultural pump sets with a capacity of up to 7.5 H.P.
**(c) Kusum Component-C: (Feeder Level Solarization)**
        *  **Target:** Solarization of 2,00,000 pump sets
        *  Solar Agricultural Livelihood Scheme (Sky) portal (www.skyrajasthan.org.in) to coordinate farmers/landowners and developers and arrange necessary land.
*   **Chief Minister Kisan Mitra Energy Scheme:**
     *  **Start:** July 17, 2021
    *   **Objective:** To provide a subsidy of ₹1000/month to agricultural consumers, with a maximum of ₹12,000 in a year.
   *   From June 2023, it has been merged into the Chief Minister's Free Electricity Scheme (Agricultural Grant)!
  *  Under which currently ---------> 2000 units of free electricity per month (to agricultural consumers)
    *     ---------> if more than 2000 units per month
       *  ---------> then a subsidy of ₹1000 in that particular month under the Chief Minister Kisan Mitra Energy Scheme

**Page 250**

*   **Rajasthan ka Bhugol**
  * 5. **Chief Minister's Free Electricity Scheme (Domestic Grant)**
       *  Implemented From: June, 2023

| Electricity Consumption  | Subsidy  |
| ------------- | -----------------|
| Up to 100 Units  |  Free Electricity |
| Up to 200 Units   |Exemption in the electricity charges, fixed charge and urban surcharge bill of the first 100 units  |
| More than 200 Units | First 100 units are free, but other charges have to be borne by the consumer |

6. **PM Surya Ghar Muft Bijli Yojana**
  * **Start:** 13 February 2024
   * **Budget:** ₹ 75,000 crore
  *  **Objective:** To install solar power plants on one crore houses to provide 300 units of free electricity every month.
  *(ii) Subsidy in this Scheme*
|1 to 2 KW|₹ 30,000 to ₹ 60,000 |
|----|----|
|3 KW|78,000 (maximum)|
 *  **Target:** The Rajasthan government has set a target of installing solar rooftop plants in 5 lakh houses.
**Page 251**
*  **Rajasthan ka Bhugol**
## **E. Other Important Points**
   ### 1. **Energy Related Policies in Rajasthan**
| Solar Energy Policy | Wind Energy Policy | Renewable Energy Policy | Biomass Policy | Rajasthan Pump Storage Policy |
|---------------------|-----------------|-----------------|------------------|-------------------|
|  2011-2019       | 2012            | 6 October, 2023   | 2010           | 23 September 2023 |
| 18 Dec, 2019 |  | Renewable Energy Policy target of 65000 MW by 2023 | | Current capacity 5(23 September 2023) |
| |  | Peak - 45000 MW | |  |
| |  |  Grid - 15000 MW| |  |
| |  |  Large Water Pump Plant - 10000 MW  | |  |
| | | Total Target - 65000 MW | |  |

###  **Rajasthan Green Hydrogen Policy**
      * 29 September, 2023
       *   Upto 31 March 2030/ Until the new policy
      *  Target of 2000 KTPA in the state by 2030 (KTPA = kilo tons per annum)

 *  **Note:** At the international level, the Government of India is committed to a target of producing 500 GW of renewable energy by 2030.

2. **Current Energy in Rajasthan:**
    *  **Installed Capacity:** 24783.64 MW (March, 2024)
         *  **Main production in which**
            *   **Thermal Energy:** - 12000 MW (approx)
            *   **Wind Energy:** 4359.63
**Page 252**
*   **Rajasthan ka Bhugol**
*  **Total electricity availability in Rajasthan by March 2024 - 243,365**
        *  **Solar Energy:** - 4010.50
        *  **Hydro/Water Energy:** - 3000 MW (Approx)
        *  **Nuclear Energy:** - 456.74
        *  **Biomass Energy:** - 103.95 MW
*  **Contribution to Rajasthan's total installed power capacity:**

|Contribution of Traditional Energy | Contribution of Renewable Energy  |
|------------------------------|-----------------|
| 78-79%  | 20-21%  |
* **NOTE:** Highest annual growth in renewable energy in 2023 - Rajasthan (First)
### 3. **Important Days Related to Energy:**
   *  **20 August** - Renewable Energy Day
   *   **14 December** - National Energy Conservation Day
        *   **Earth Hour** - It is celebrated on any Saturday of March from 8:30-9:30 pm.
            *   On that day, an appeal is made to turn off all equipment except the necessary equipment.
           *   It was started in Australia to give the message of environmental protection and energy saving, in which India joined in 2009.
**Page 253**
*   **Rajasthan ka Bhugol**
